platform :ios, '8.0'
target 'qingsonghuan' do
pod 'MBProgressHUD', '~> 1.1.0'
pod 'MJRefresh', '~> 3.1.15.3'
pod 'AFNetworking', '~> 3.2.0'
pod 'IQKeyboardManager', '~> 6.0.2'
pod 'Masonry', '~> 1.1.0'
pod 'LMAlertView', '~> 1.1.0'
end
